image: gcc

cache: 
  paths:
  - linux-centos6/*
  
  
stages:
  - build
  - test  

build:
  stage: build
  before_script:
  - source ./scripts/gitlab_ci/defaults.sh
  - chmod +x ./scripts/gitlab_ci/build-deps-from-source-centos6.sh
  - ./scripts/gitlab_ci/build-deps-from-source-centos6.sh 

  script:
  #- make all
  #- make test
  #- make runtest
  - ./scripts/gitlab_ci/setup-venv.sh `pwd`/venv

  - source `pwd`/venv/bin/activate
  - ./scripts/gitlab_ci/install-python-deps.sh
  - ./scripts/gitlab_ci/configure.sh
  - echo "INCLUDE_DIRS :=  `pwd`/linux-centos6/include \$(PYTHON_INCLUDE) \$(INCLUDE_DIRS)" >> Makefile.config
  - echo "LIBRARY_DIRS :=  `pwd`/linux-centos6/lib \$(PYTHON_LIB) \$(LIBRARY_DIRS)" >> Makefile.config
  - echo "BLAS_INCLUDE := `pwd`/linux-centos6/include" >> Makefile.config
  - echo "BLAS_LIB :=  `pwd`/linux-centos6/lib" >> Makefile.config
  - echo "CUDA_DIR := /opt/cuda-8.0" >> Makefile.config
  - echo "PROTOBUF_LIBRARY := `pwd`/linux-centos6/lib/libprotobuf.so" >> Makefile.config
  - echo "PROTOBUF_INCLUDE_DIR := `pwd`/linux-centos6/include" >> Makefile.config
  - echo "PROTOBUF_LIB := `pwd`/linux-centos6/include" >> Makefile.config
  - echo "INCLUDE_DIRS := /opt/opencv-2.4.9-x86_64/include \$(INCLUDE_DIRS)" >> Makefile.config
  - echo "LIBRARY_DIRS :=  /opt/opencv-2.4.9-x86_64/lib \$(LIBRARY_DIRS)" >> Makefile.config
  - echo "USE_PKG_CONFIG  :=  1" >> Makefile.config
  #- echo "PROTOBUF_LIBRARY := /opt/protobuf-2.6.1-x86_64/lib/libprotobuf.so" >> Makefile.config
  #- echo "PROTOBUF_INCLUDE_DIR := /opt/protobuf-2.6.1-x86_64/include" >> Makefile.config
  #- echo "PROTOBUF_LIB := /opt/protobuf-2.6.1-x86_64/lib" >> Makefile.config
  #- echo "INCLUDE_DIRS :=  \$(PROTOBUF_INCLUDE_DIR) \$(INCLUDE_DIRS)" >> Makefile.config
  #- echo "LIBRARY_DIRS :=  \$(PROTOBUF_LIB) \$(LIBRARY_DIRS)" >> Makefile.config
  - cat Makefile.config
  - ls linux-centos6/include
  - NUM_THREADS=1 ./scripts/gitlab_ci/build.sh
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths: 
    - linux-centos6/lib
    - linux-centos6/include
    - linux-centos6/bin
  artifacts:
    paths:
    - build
    - distribute

test:
  stage: test
  script:
  - ./scripts/gitlab_ci/test.sh
  